### PR TITLE
Round up fee and distance, remove authorize, and change request JSON

### PR DESCRIPTION
**Pull request by arizalpratama**
merge to main

### CODE REVIEW

**Comment by mystald** [comment]
ada screenshot hasil `GetShipmentFee` nya? dari swagger coba @arizalpratama

**Comment by arizalpratama** [comment]
image

Studi kasus input data 1:
- CostKg: 1000
- CostKm: 1000
- Distance: 60KM
- Weight: 12.5

Calculation:  (60*1000) + (12.5 * 1000) = 73.500

**Comment by arizalpratama** [comment]
image

Studi kasus input data 2:
- CostKg: 1000
- CostKm: 1000
- Distance: 60KM
- Weight: 12.3

Calculation:  (60*1000) + (12.3 * 1000) = 73.500 (done Round Up 500)

**Review by mystald — APPROVED** [review]
BB-8 Thumbs Up

**Pull request merged**
